# This file describes a Fastly Compute@Edge package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = ["jchampion@fastly.com"]
description = ""
language = "javascript"
manifest_version = 3
name = "target"
service_id = ""

[scripts]
  build = "npm run build:production"
  post_init = "npm install"
